# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20150410_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.IntegerField(choices=[(0, '\u0417\u041d\u0423'), (1, '\u0417\u041d\u0422\u0423'), (2, '\u041a\u041f\u0423')], default=0, verbose_name=b'\xd0\xa3\xd0\xbd\xd0\xb8\xd0\xb2\xd0\xb5\xd1\x80\xd1\x81\xd0\xb8\xd1\x82\xd0\xb5\xd1\x82'),
        ),
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, verbose_name=b'\xd0\x9a\xd1\x83\xd1\x80\xd1\x81'),
        ),
        migrations.AlterField(
            model_name='user',
            name='faculty',
            field=models.IntegerField(choices=[(0, '\u0436\u0443\u0440\u043d\u0430\u043b\u0456\u0441\u0442\u0438\u043a\u0438'), (1, '\u0431\u0456\u043e\u043b\u043e\u0433\u0456\u0447\u043d\u0438\u0439'), (2, '\u0456\u043d\u043e\u0437\u0435\u043c\u043d\u043e\u0457 \u0444\u0456\u043b\u043e\u043b\u043e\u0433\u0456\u0457'), (3, '\u0444\u0456\u0437\u0438\u0447\u043d\u043e\u0433\u043e \u0432\u0438\u0445\u043e\u0432\u0430\u043d\u043d\u044f'), (4, '\u0456\u0441\u0442\u043e\u0440\u0438\u0447\u043d\u0438\u0439'), (5, '\u043c\u0430\u0442\u0435\u043c\u0430\u0442\u0438\u0447\u043d\u0438\u0439'), (6, '\u044e\u0440\u0438\u0434\u0438\u0447\u043d\u0438\u0439'), (7, '\u043c\u0435\u043d\u0435\u0434\u0436\u043c\u0435\u043d\u0442\u0443'), (8, '\u0444\u0456\u043b\u043e\u043b\u043e\u0433\u0456\u0447\u043d\u0438\u0439'), (9, '\u0444\u0456\u0437\u0438\u0447\u043d\u0438\u0439'), (10, '\u0441\u043e\u0446\u0456\u0430\u043b\u044c\u043d\u043e\u0457 \u043f\u0435\u0434\u0430\u0433\u043e\u0433\u0456\u043a\u0438 \u0442\u0430 \u043f\u0441\u0438\u0445\u043e\u043b\u043e\u0433\u0456\u0457'), (11, '\u0441\u043e\u0446i\u043e\u043b\u043e\u0433i\u0457 \u0442\u0430 \u0443\u043f\u0440\u0430\u0432\u043bi\u043d\u043d\u044f'), (12, '\u0435\u043a\u043e\u043d\u043e\u043c\u0456\u0447\u043d\u0438\u0439'), (13, '\u0415\u041f\u041a')], default=0, verbose_name=b'\xd0\xa4\xd0\xb0\xd0\xba\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82\xd0\xb5\xd1\x82'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hash_code',
            field=models.CharField(blank=True, max_length=200, verbose_name=b'Secret Key'),
        ),
    ]
