# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20160121_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ip_user',
            new_name='ip',
        ),
    ]
