# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20160122_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_started',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\x9f\xd1\x80\xd0\xbe\xd1\x81\xd0\xbc\xd0\xbe\xd1\x82\xd1\x80\xd0\xb5\xd0\xbb \xd0\xbb\xd0\xb8 \xd1\x81\xd1\x82\xd1\x80\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x86\xd1\x83 \xd0\xb2 \xd1\x81\xd0\xb0\xd0\xbc\xd0\xbe\xd0\xbc \xd0\xbd\xd0\xb0\xd1\x87\xd0\xb0\xd0\xbb\xd0\xb5'),
        ),
    ]
